parameters:
    admin.user.class: %success_admin.user_admin%
    entity.user.class: %success_admin.user_model%
    controller.user.class: %success_admin.user_controller%
    
    admin.group.class: %success_admin.group_admin%
    entity.group.class: %success_admin.group_model%
    controller.group.class: %success_admin.group_controller%    
    
    form.type.security_roles.class: Success\AdminBundle\Form\Type\SecurityRolesType


services:
#    admin.example:
#        class: %admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    success.admin.user:
        class: %admin.user.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: 'Usuarios', label: Usuarios }
        arguments:
            - null
            - %entity.user.class%
            - %controller.user.class%
            
    success.admin.group:
        class: %admin.group.class%
        tags:
          - { name: sonata.admin, manager_type: orm, group: 'Usuarios', label: Grupos }
        arguments:
            - null
            - %entity.group.class%
            - %controller.group.class%
            
    success.user.form.type.security_roles:
        class: %form.type.security_roles.class%
        tags:
          - { name: form.type, alias: success_security_roles }
        arguments: 
            - @sonata.admin.pool
